### ISSUE TITLE
[question] Do we have to use Tracker.auto all the time?

### ISSUE THREAD

**Issue by wuxianliang** [FocusSchoolSoftware/fss-postgres#1]
Dear @nothingisdead 
I am using fss-postgres and I noticed the difference between putting 

``` livescript
results = handle.fetch!
console.log results
```

in Tracker.auto and outside. 
When inside, I could see all the results. When outside, I received an empty array. So do we have to put them inside all the time? I mean every time we need data from Postgres, we write a Tracker.auto for fetching data.

Thank you.

**Comment by nothingisdead** [comment]
Hi,

Currently, the return value of `Postgres.subscribe` is a slightly modified `ReactiveVar`, so you can use it as described in the [docs](http://docs.meteor.com/#/full/reactivevar_pkg). The only differences are the `stop` method, to stop the subscription, and the `fetch` method, which is just an alias of `get`.

So no, you don't have to use `Tracker.autorun` necessarily, but you do have to call it inside of a reactive computation if you want it to be re-run when the results update. (The most common scenario would be to call it from inside a Template helper.)

**Comment by wuxianliang** [comment]
Thank you!
